export const GET_CITY_IMG = "GET_CITY_IMG";
export const GET_CITY_IMG_PENDING = "GET_CITY_IMG_PENDING";
export const GET_CITY_IMG_REJECTED = "GET_CITY_IMG_PENDING";
export const GET_CITY_IMG_FULFILLED = "GET_CITY_IMG_FULFILLED";
