export const SWITCH_MEDIA_WIKI_IMG = "SWITCH_MEDIA_WIKI_IMG";
export const SWITCH_BACKGROUND_VIDEO = "SWITCH_BACKGROUND_VIDEO";
export const SWITCH_WEATHER_INFOS = "SWITCH_WEATHER_INFOS";
export const OPEN_PARAMETERS = "OPEN_PARAMETERS";
export const CLOSE_PARAMETERS = "CLOSE_PARAMETERS";
export const CHANGE_REFRESH_INTERVAL = "CHANGE_REFRESH_INTERVAL";
