export const SWITCH_MEDIA_WIKI_IMG = "SWITCH_MEDIA_WIKI_IMG";
export const SWITCH_BACKGROUND_VIDEO = "SWITCH_BACKGROUND_VIDEO";
export const SWITCH_WEATHER_INFOS = "SWITCH_WEATHER_INFOS";
export const CHANGE_REFRESH_INTERVAL = "CHANGE_REFRESH_INTERVAL";
export const SWITCH_SETTINGS_VISIBILITY = "SWITCH_SETTINGS_VISIBILITY";
