export const GET_TODAY_WEATHER = "GET_TODAY_WEATHER";
export const GET_TODAY_WEATHER_PENDING = "GET_TODAY_WEATHER_PENDING";
export const GET_TODAY_WEATHER_REJECTED = "GET_TODAY_REJECTED";
export const GET_TODAY_WEATHER_FULFILLED = "GET_TODAY_WEATHER_FULFILLED";
