export const GET_TODAY_WEATHER = "GET_TODAY_WEATHER";
export const GET_TODAY_WEATHER_PENDING = "GET_TODAY_WEATHER_PENDING";
export const GET_TODAY_WEATHER_REJECTED = "GET_TODAY_WEATHER_REJECTED";
export const GET_TODAY_WEATHER_FULFILLED = "GET_TODAY_WEATHER_FULFILLED";

export const GET_FORECAST_WEATHER = "GET_FORECAST_WEATHER";
export const GET_FORECAST_WEATHER_PENDING = "GET_FORECAST_WEATHER_PENDING";
export const GET_FORECAST_WEATHER_REJECTED = "GET_FORECAST_WEATHER_REJECTED";
export const GET_FORECAST_WEATHER_FULFILLED = "GET_FORECAST_WEATHER_FULFILLED";
